# @author: Santoh Vasa
# Name: Santosh Vasa<br>
# Date: September 25, 2022<br>
# Class: Advanced Perception

dataset:
    data_dir:
        train: '/home/sid/datasets/maps/train'
        val: '/home/sid/datasets/maps/val'
    batch_size: 1
visualize: false
