# @author: Santoh Vasa
# Name: Santosh Vasa<br>
# Date: September 25, 2022<br>
# Class: Advanced Perception

dataset:
    data_dir:
        train: 'C:\Users\santo\workspace\str\data\maps\train'
        val: 'C:\Users\santo\workspace\str\data\maps\val'
    batch_size: 1
visualize: true
